# Generated by Django 3.1.4 on 2021-01-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commentfavorrecord_commentrecord_newsfavorrecord_viewerrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(max_length=128, null=True, verbose_name='头像'),
        ),
    ]
