# Generated by Django 3.1.4 on 2021-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210306_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='follow',
            field=models.ManyToManyField(blank=True, to='api.UserInfo', verbose_name='关注'),
        ),
    ]
