# Generated by Django 3.1.4 on 2021-03-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210307_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=16, verbose_name='商品名称')),
                ('product_info', models.CharField(max_length=255, verbose_name='商品详情')),
                ('wx_phone', models.CharField(max_length=16, verbose_name='联系方式')),
                ('address', models.CharField(max_length=128, verbose_name='位置')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('collect_count', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('datatime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('pro_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.userinfo', verbose_name='发布者')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewerFavorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinforecord', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCollectFavorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinforecord', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(5, '书籍'), (7, '其他'), (2, '电子数码'), (4, '美容护肤'), (3, '复习资料'), (6, '体育用具'), (1, '生活用品')], max_length=16, verbose_name='分类')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinforecord', verbose_name='商品')),
            ],
        ),
    ]
